version: '3.9'

services:
  db:
    image: postgres:17-alpine
    container_name: bank_db
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank_app
    env_file: .env
    ports:
      - 8000:8080
    restart: on-failure
    healthcheck:
      test: ["CMD", "wget", "--spider", "--timeout=5", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 3

volumes:
  db-data:
