server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankcards_db
    username: postgres
    password: Dima_2145
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      format_sql: true


encrypt:
  key: ${ENCRYPT_KEY}

security:
  jwt:
    secret: ${SECURITY_SECRET_KEY}
    expiration-ms: 86400000